packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': 5.4.1
  '@hono/node-server': 1.19.5
  '@hono/zod-openapi': 1.1.4
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@tailwindcss/vite': 4.1.17
  '@tanstack/react-devtools': 0.7.11
  '@tanstack/react-router': 1.134.18
  '@tanstack/react-router-devtools': 1.134.18
  '@tanstack/react-router-ssr-query': 1.134.18
  '@tanstack/react-start': 1.134.18
  '@tanstack/router-plugin': 1.134.18
  '@types/node': 24.10.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@vitejs/plugin-react': 5.1.0
  eslint: 9.37.0
  hono: 4.9.10
  jsdom: 27.1.0
  openapi-fetch: 0.15.0
  openapi-typescript: 7.10.1
  prettier-plugin-packagejson: 2.5.19
  prettier: 3.6.2
  react-dom: 19.2.0
  react: 19.2.0
  tailwindcss: 4.1.17
  tsdown: 0.15.6
  tsx: 4.20.6
  typescript: 5.9.3
  vite: 7.2.2
  zod: 4.1.12
