packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': 5.4.1
  '@hono/node-server': 1.19.5
  '@trivago/prettier-plugin-sort-imports': 5.2.2
  eslint: 9.37.0
  hono: 4.9.10
  prettier: 3.6.2
  prettier-plugin-packagejson: 2.5.19
  tsdown: 0.15.6
  tsx: 4.20.6
  typescript: 5.9.3
