packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': 5.4.1
  '@hono/node-server': 1.19.5
  '@hono/zod-openapi': ^1.1.4
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@types/node': 24.10.0
  eslint: 9.37.0
  hono: 4.9.10
  openapi-fetch: 0.15.0
  openapi-typescript: 7.10.1
  prettier-plugin-packagejson: 2.5.19
  prettier: 3.6.2
  tsdown: 0.15.6
  tsx: 4.20.6
  typescript: 5.9.3
  zod: ^4.1.12
