packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': 6.2.0
  '@eslint-react/eslint-plugin': 2.3.4
  '@hono/node-server': 1.19.5
  '@hono/zod-openapi': 1.1.4
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@scalar/hono-api-reference': 0.9.24
  '@tailwindcss/vite': 4.1.17
  '@tanstack/react-devtools': 0.7.11
  '@tanstack/react-router': 1.134.18
  '@tanstack/react-router-devtools': 1.134.18
  '@tanstack/react-router-ssr-query': 1.134.18
  '@tanstack/react-start': 1.134.18
  '@tanstack/router-plugin': 1.134.18
  '@types/node': 24.10.0
  '@types/pg': 8.15.6
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@vitejs/plugin-react': 5.1.0
  drizzle-kit: 1.0.0-beta.1-69a2ca0
  drizzle-orm: 1.0.0-beta.2-6565b14
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.24
  eslint: 9.38.0
  hono: 4.10.3
  jsdom: 27.1.0
  nx: 21.6.3
  openapi-fetch: 0.15.0
  openapi-typescript: 7.10.1
  pg: 8.16.3
  prettier-plugin-packagejson: 2.5.19
  prettier: 3.6.2
  react-dom: 19.2.0
  react: 19.2.0
  tailwindcss: 4.1.17
  tsup: 8.5.0
  tsx: 4.20.6
  typescript: 5.9.3
  uuidv7: 1.0.2
  vite: 7.2.2
  zod: 4.1.12
